// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections.Generic;

public class  WorkoutData
{
	public class Row
	{
		public string id;
		public string voice;
		public string sfx;
		public string commands;
		public string phase;
		public string show;
		public string hide;
		public string zoom;
		public string position;
		public string zoomDelay;
		public string positionDelay;
	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}
    public void Load(TextAsset csv)
	{
        Load(csv.text);
    }
	public void Load(string text)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.id = grid[i][0];
			row.voice = grid[i][1];
			row.sfx = grid[i][2];
			row.commands = grid[i][3];
			row.phase = grid[i][4];
			row.show = grid[i][5];
			row.hide = grid[i][6];
			row.zoom = grid[i][7];
			row.position = grid[i][8];
			row.zoomDelay = grid[i][9];
			row.positionDelay = grid[i][10];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}
}